### ISSUE TITLE
Failed arm build on amd64 builder

### ISSUE THREAD

**Issue by andvikt** [home-assistant/builder#105]
When I build my add-on using builder action I have this error:
`The requested image's platform (linux/arm) does not match the detected host platform (linux/amd64) and no specific platform was requested`

My add-on is: https://github.com/andvikt/mega_addon/tree/master/mega-updater

I can't figure out how to tell builder to use proper architecture.

**Comment by ludeeus** [comment]
That is not an error, that is a warning and it does not impact the build at all, you can ignore that.
