### ISSUE TITLE
YAML Support

### ISSUE THREAD

**Issue by ikifar2012** [home-assistant/builder#129]
Upon trying to convert an addon's config files from JSON to YAML I get the following error from the builder  
`jq: error: Could not open file /tmp/build_config/config.json: No such file or directory`
Is YAML supported by the builder action?

**Comment by ludeeus** [comment]
Yes, that was added in https://github.com/home-assistant/builder/pull/107 and released in https://github.com/home-assistant/builder/releases/tag/2021.09.0
