### ISSUE TITLE
previously trusted Community Attestation Service changed its signature.

### ISSUE THREAD

**Issue by tux2000** [home-assistant/builder#153]
Got the following error multiple times in a test-build pipeline:
```
Error: operation aborted : rpc error: code = Canceled desc = signature doesn't match provided public key
previously trusted Community Attestation Service changed its signature. In order to trust again the server please provide a new public key or remove .cas-trusted-signing-pub-key stored in home folder.
```

This was not mitigated by using the `--no-cache` argument (#147) nor by using a previous version of the workflow (`2022.06.2`)

Full logs:
https://github.com/tux2000/home-assistant-addons/runs/7177396932?check_suite_focus=true
https://github.com/tux2000/home-assistant-addons/runs/7177672867?check_suite_focus=true
https://github.com/tux2000/home-assistant-addons/runs/7178171929?check_suite_focus=true

**Comment by ludeeus** [comment]
Was due to maintenance, see <https://github.com/codenotary/cas/issues/273>

**Comment by tux2000** [comment]
Great, i can confirm that restarting a previously failed workflow run now passed the problem... :)
