### ISSUE TITLE
Upload failed on ghcr.io, no details

### ISSUE THREAD

**Issue by bokub** [home-assistant/builder#177]
Hello,

I'm currently trying to use this repo as a GitHub Action, here is my workflow:

```yaml
  publish:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: bokub
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target . \
            --docker-hub ghcr.io/bokub
```

Whenever the Action runs, the login step succeeds, then the build step fails with the following output:

```
[10:43:47] INFO: Finish build for ghcr.io/bokub/my-addon-i386:0.1.0
[10:43:47] INFO: Create image tag: latest
[10:43:47] INFO: Start upload of ghcr.io/bokub/my-addon-i386:0.1.0 (attempt #1/3)
[10:43:47] WARNING: Upload failed on attempt #1
[10:43:47] WARNING: Upload failed on attempt #1
[10:44:17] INFO: Start upload of ghcr.io/bokub/my-addon-amd64:0.1.0 (attempt #2/3)
[10:44:17] WARNING: Upload failed on attempt #2
[10:44:17] INFO: Start upload of ghcr.io/bokub/my-addon-i386:0.1.0 (attempt #2/3)
[10:44:18] WARNING: Upload failed on attempt #2
[10:44:47] INFO: Start upload of ghcr.io/bokub/my-addon-amd64:0.1.0 (attempt #3/3)
[10:44:48] FATAL: Upload failed on attempt #3
[10:44:48] INFO: Start upload of ghcr.io/bokub/my-addon-i386:0.1.0 (attempt #3/3)
[10:44:48] FATAL: Upload failed on attempt #3
...
```

Did I do something wrong?
 Is there any way to **display the upload error**? ("Upload failed" is not enough to understand what went wrong)

Thanks!

**Comment by bokub** [comment]
Looks like the default `GITHUB_TOKEN` doesn't have enough rights.

I had to create a Personal Access Token and use it instead

**Comment by klaernie** [comment]
The default GITHUB_TOKEN works, if you link the repository doing the build to the package and grant the actions running the repository write access. I'm doing exactly this in https://github.com/klaernie/hassio-addons/blob/main/.github/workflows/ci.yml
The only sad part is, that you cannot create a package in Github without pushing an image, and without granting access you cannot write from Github actions. I solved that catch-22 by manually pushing an image, sorting the permissions out and then running my Github actions.

**Comment by Erudition** [comment]
Uh oh! This needs to be re-opened. I built an addon with the starter template, and I'm running into the same issue. Not only does the error message still need to be clarified, but it would be nice to have some documentation on how to use @klaernie 's workaround or something.

**Comment by Erudition** [comment]
According to this the linking is done automatically:

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#pushing-container-images

However it "recommends" adding this to the Dockerfile for that:
`LABEL org.opencontainers.image.source=https://github.com/you/repo-here`

but... that didn't do the trick.

**Comment by Erudition** [comment]
Created a PR for the fixes. 
https://github.com/home-assistant/addons-example/pull/85

Note that this issue still applies, the error message does not indicate what went wrong.
