### ISSUE TITLE
Option to use another docker registry than Docker Hub

### ISSUE THREAD

**Issue by MexHigh** [home-assistant/builder#184]
I want to build images that get pushed to my own repository hosted in GitLab instead of Docker hub. It seems like the `--docker-hub` flag (and corresponding credential flags) only apply to Docker Hub.

**Comment by agners** [comment]
The string will be passed to the Docker command line directly as the container repository part of the image name directly. So you should be able to use the GitLab registry just fine with that flag.

**Comment by MexHigh** [comment]
Does not work for me, it's failing at the login part.

My command line: `docker run --rm --privileged -v ~/.docker:/root/.docker -v $(pwd):/data homeassistant/amd64-builder --aarch64 -t /data --docker-hub registry.<redacted> --docker-user <redacted> --docker-password <redacted>`

The error: `Error response from daemon: Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password`

At https://github.com/home-assistant/builder/blob/master/builder.sh#L956, the registry is not passed to the `docker login` command, so docker hub is used.

Sorry for the lack of information in my issue.

**Comment by klaernie** [comment]
@MexHigh If you do not provide `--docker-user` and `--docker-password`, but manually run the correct `docker login` command before, it will work. I use this [in my addons-repo](https://github.com/klaernie/hassio-addons/blob/main/.github/workflows/ci.yml#L32-L41) to push to ghcr.io
