### ISSUE TITLE
Bump Alpine OS version to 3.19

### ISSUE THREAD

**Issue by lukasz-burak** [home-assistant/builder#190]
Currently image is using Alpine OS v.3.18.
New 3.19 version was released, can you upgrade to use that?
This is required to allow some downstream ha-addons to support new hardware.

**Comment by agners** [comment]
This is just about what Alpine version the builder is using.

If you build an add-on, you are using the Docker base image. 3.19 is available, see https://github.com/home-assistant/docker-base/.
